language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="ArduinoPhysik"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit GFX Library"
   - arduino --install-library "Adafruit SSD1306"
   - arduino --install-library "DHT sensor library"
   - arduino --install-library "Keypad"
   - arduino --install-library "HCSR04"
   - arduino --install-library "Sparkfun BMP180"
script:
   - build_main_platforms