language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="ArduinoPhysik"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit GFX Library"
   - arduino --install-library "Adafruit SSD1306"
   - arduino --install-library "DHT sensor library"
   - arduino --install-library "Keypad"
   - arduino --install-library "HCSR04"
   #- if [! -d "$HOME/arduino_ide/libraries/BMP180" ]; then git clone https://github.com/sparkfun/BMP180_Breakout_Arduino_Library.git $HOME/arduino_ide/libraries/BMP180; fi
   #- if [! -d "$HOME/arduino_ide/libraries/BigNumber" ]; then git clone https://github.com/leonardoInf/BigNumber.git $HOME/arduino_ide/libraries/BigNumber; fi
    - git clone https://github.com/sparkfun/BMP180_Breakout_Arduino_Library.git $HOME/arduino_ide/libraries/BMP180
    - git clone https://github.com/leonardoInf/BigNumber.git $HOME/arduino_ide/libraries/BigNumber
script:
   - build_main_platforms
